---
- name: "Set up keepalived"
  hosts: all
  gather_facts: yes
  become: true
  become_method: sudo
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
  pre_tasks:
    - name: Display the configuration
      debug:
        var: keepalived_instances
  roles:
    - ansible-keepalived
